easy_admin:
    entities:
        # List the entity class name you want to manage
        Carousel:
          class: App\Entity\Carousel
          label: 'Carousel Infos'
          list:
            fields: ['title', 'description', 'link', 'img']
          form:
            fields: ['title', 'description', 'link', { property: 'imgFile', type: 'file', label: "Fond d'ecran"}]
        WidgetBlock:
          class: App\Entity\WidgetBlock
          label: 'Widget Block Infos'
          list:
            fields: ['blockTitle', 'linkTitle', 'img']
          form:
            fields: ['blockTitle', 'linkTitle', 'linkUrl', { property: 'imgFile', type: 'file', label: "Fond d'ecran du block"}]   
